package config

import (
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"strings"
)

// Env is the configuration of the API service. On the server it comes from /etc/krokosha/env
// through systemd's EnvironmentFile (deploy/env/.env.example describes every variable).
type Env struct {
	// Listen is the address of the HTTP server. Always loopback: nginx is the only client.
	Listen string
	// SiteURL is the public origin of the site, e.g. https://krokosha.xyz.
	SiteURL string
	// AdminPath is the hidden prefix of the admin area, e.g. /_k7f3a9 (brief B6).
	AdminPath string
	// ContentDir points to content/ of the installed repository.
	ContentDir string
	// DataDir is the root of everything that must survive a migration (docs/architecture.md §6).
	DataDir string
	// StateDir holds what can be rebuilt: caches, the report of the last site build, requests
	// to the build (the «rebuild now» button).
	StateDir string
	// WWWDir is where the releases of the site live; «current» points to the live one.
	WWWDir string
	// AccessLog is nginx's JSON access log, the source of the «server traffic» screen.
	AccessLog string

	MySQL MySQL
	// RedisURL may be empty: the service then keeps rate limits and live data in memory.
	RedisURL string
	// Secret signs what must not be forged: proof-of-work challenges of the contact form, reply
	// addresses of requests. Generated by install.sh; every signature dies with it.
	Secret string
	// Mail is how notifications and replies are sent. Without it they wait in the outbox.
	Mail Mail
	// Retention is how long requests are kept (brief B10.7).
	Retention Retention
	// Telegram is the bot requests are worked with in (brief B10.3). Without a token there is none.
	Telegram Telegram

	LogLevel string
}

// Telegram holds the settings of the bot.
type Telegram struct {
	Token string // TELEGRAM_BOT_TOKEN, from @BotFather; lives in /etc/krokosha/env and nowhere else
	Mode  string // TELEGRAM_MODE: webhook (Telegram calls the site, the default) | polling (the site asks Telegram)
	API   string // TELEGRAM_API_URL: where the Bot API is; only tests and staging point elsewhere
}

// Retention holds the rule for old requests. The privacy page promises 24 months: a longer
// period here must be written there first.
type Retention struct {
	KeepMonths int  // LEADS_KEEP_MONTHS: after so many months without activity a request expires; 0 — never
	Delete     bool // LEADS_EXPIRED=delete: expired requests are deleted; the default, anonymize, keeps the statistics
	SpamDays   int  // LEADS_SPAM_DAYS: what the spam filter caught is deleted after so many days; 0 — never
}

// Mail holds the settings of outgoing mail.
type Mail struct {
	SMTPAddr string // host:port of the submission service; empty = mail is not set up yet
	User     string
	Password string
	From     string // «Denis Humen <denis@krokosha.xyz>»
	NotifyTo string // where notifications about new requests go
}

// MySQL holds the connection parameters of the main database.
type MySQL struct {
	Addr     string // host:port
	Database string
	User     string
	Password string
}

var reBotToken = regexp.MustCompile(`^[0-9]{5,}:[A-Za-z0-9_-]{30,}$`)

var reAdminPath = regexp.MustCompile(`^/[A-Za-z0-9_-]{4,64}$`)

// LoadEnv reads the configuration from environment variables and validates it.
// lookup is os.LookupEnv in production; tests pass their own.
func LoadEnv(lookup func(string) (string, bool)) (*Env, error) {
	get := func(key, fallback string) string {
		if value, ok := lookup(key); ok && strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
		return fallback
	}

	env := &Env{
		Listen:     get("KROKOSHA_LISTEN", "127.0.0.1:8080"),
		SiteURL:    strings.TrimRight(get("SITE_URL", ""), "/"),
		AdminPath:  strings.TrimRight(get("ADMIN_PATH", ""), "/"),
		ContentDir: get("KROKOSHA_CONTENT_DIR", "/opt/krokosha/repo/content"),
		DataDir:    get("KROKOSHA_DATA", "/srv/krokosha"),
		StateDir:   get("KROKOSHA_STATE", "/var/lib/krokosha"),
		WWWDir:     get("KROKOSHA_WWW", "/var/www/krokosha"),
		AccessLog:  get("KROKOSHA_ACCESS_LOG", "/var/log/krokosha/nginx-access.json.log"),
		RedisURL:   get("REDIS_URL", ""),
		Secret:     get("APP_SECRET", ""),
		Mail: Mail{
			SMTPAddr: get("SMTP_ADDR", ""),
			User:     get("SMTP_USER", ""),
			Password: get("SMTP_PASSWORD", ""),
			From:     get("MAIL_FROM", ""),
			NotifyTo: get("MAIL_NOTIFY_TO", ""),
		},
		Telegram: Telegram{
			Token: get("TELEGRAM_BOT_TOKEN", ""),
			Mode:  strings.ToLower(get("TELEGRAM_MODE", "webhook")),
			API:   strings.TrimRight(get("TELEGRAM_API_URL", ""), "/"),
		},
		LogLevel: strings.ToLower(get("KROKOSHA_LOG_LEVEL", "info")),
		MySQL: MySQL{
			Addr:     get("MYSQL_ADDR", "127.0.0.1:3306"),
			Database: get("MYSQL_DATABASE", "krokosha"),
			User:     get("MYSQL_USER", "krokosha"),
			Password: get("MYSQL_PASSWORD", ""),
		},
	}

	var problems []string
	number := func(key string, fallback, most int) int {
		value, err := strconv.Atoi(get(key, strconv.Itoa(fallback)))
		if err != nil || value < 0 || value > most {
			problems = append(problems, fmt.Sprintf("%s must be a number from 0 to %d", key, most))
			return fallback
		}
		return value
	}
	env.Retention.KeepMonths = number("LEADS_KEEP_MONTHS", 24, 240)
	env.Retention.SpamDays = number("LEADS_SPAM_DAYS", 30, 3650)
	switch expired := strings.ToLower(get("LEADS_EXPIRED", "anonymize")); expired {
	case "anonymize":
	case "delete":
		env.Retention.Delete = true
	default:
		problems = append(problems, "LEADS_EXPIRED must be anonymize or delete")
	}
	if host, _, err := net.SplitHostPort(env.Listen); err != nil {
		problems = append(problems, fmt.Sprintf("KROKOSHA_LISTEN: %v", err))
	} else if ip := net.ParseIP(host); host != "localhost" && (ip == nil || !ip.IsLoopback()) {
		// The API trusts X-Real-IP from its only client, nginx. Exposed directly, anyone could forge it.
		problems = append(problems, "KROKOSHA_LISTEN must be a loopback address: the service is reached only through nginx")
	}
	if parsed, err := url.Parse(env.SiteURL); err != nil || parsed.Host == "" || (parsed.Scheme != "https" && parsed.Scheme != "http") {
		problems = append(problems, "SITE_URL must be the public origin of the site, e.g. https://example.com")
	}
	if !reAdminPath.MatchString(env.AdminPath) {
		problems = append(problems, "ADMIN_PATH must look like /_k7f3a9 (letters, digits, - and _, at least 4 characters)")
	}
	if env.MySQL.Password == "" {
		problems = append(problems, "MYSQL_PASSWORD is required")
	}
	if len(env.Secret) < 32 {
		problems = append(problems, "APP_SECRET must be at least 32 characters (install.sh generates it: openssl rand -hex 32)")
	}
	if env.Mail.SMTPAddr != "" {
		if _, _, err := net.SplitHostPort(env.Mail.SMTPAddr); err != nil {
			problems = append(problems, "SMTP_ADDR must look like 127.0.0.1:587")
		}
		if _, err := mail.ParseAddress(env.Mail.From); err != nil {
			problems = append(problems, "MAIL_FROM must be an address like «Name <name@example.com>» when SMTP_ADDR is set")
		}
		if _, err := mail.ParseAddress(env.Mail.NotifyTo); err != nil {
			problems = append(problems, "MAIL_NOTIFY_TO must be an email address when SMTP_ADDR is set")
		}
	}
	if env.Telegram.Token != "" {
		if !reBotToken.MatchString(env.Telegram.Token) {
			problems = append(problems, "TELEGRAM_BOT_TOKEN does not look like a token from @BotFather (123456789:AA…)")
		}
		switch env.Telegram.Mode {
		case "polling":
		case "webhook":
			// Telegram delivers to HTTPS only.
			if !strings.HasPrefix(env.SiteURL, "https://") {
				problems = append(problems, "TELEGRAM_MODE=webhook needs an https:// SITE_URL; use TELEGRAM_MODE=polling")
			}
		default:
			problems = append(problems, "TELEGRAM_MODE must be webhook or polling")
		}
		if env.Telegram.API != "" {
			if parsed, err := url.Parse(env.Telegram.API); err != nil || parsed.Host == "" || (parsed.Scheme != "https" && parsed.Scheme != "http") {
				problems = append(problems, "TELEGRAM_API_URL must be an address like https://api.telegram.org")
			}
		}
	}
	if env.RedisURL != "" {
		if parsed, err := url.Parse(env.RedisURL); err != nil || (parsed.Scheme != "redis" && parsed.Scheme != "rediss" && parsed.Scheme != "unix") {
			problems = append(problems, "REDIS_URL must look like redis://:password@127.0.0.1:6379/0")
		}
	}
	switch env.LogLevel {
	case "debug", "info", "warn", "error":
	default:
		problems = append(problems, "KROKOSHA_LOG_LEVEL must be debug, info, warn or error")
	}
	if len(problems) > 0 {
		return nil, errors.New("configuration: " + strings.Join(problems, "; "))
	}
	return env, nil
}

// LoadEnvFromOS is LoadEnv over the process environment.
func LoadEnvFromOS() (*Env, error) {
	return LoadEnv(os.LookupEnv)
}
