// Command genlangcolors refreshes ../../langcolors.tsv from GitHub Linguist.
//
//	cd api/internal/githubsync && go generate
//
// The REST API reports only the name of a repository's language; the colour of the dot comes from
// Linguist's languages.yml (MIT License, https://github.com/github-linguist/linguist).
package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"

	"go.yaml.in/yaml/v3"
)

const source = "https://raw.githubusercontent.com/github-linguist/linguist/main/lib/linguist/languages.yml"

var hexColor = regexp.MustCompile(`^#[0-9a-fA-F]{6}$`)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, source, nil)
	if err != nil {
		return err
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: %s", source, response.Status)
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, 8<<20))
	if err != nil {
		return err
	}

	var languages map[string]struct {
		Color string `yaml:"color"`
	}
	if err := yaml.Unmarshal(data, &languages); err != nil {
		return err
	}

	names := make([]string, 0, len(languages))
	for name, language := range languages {
		if hexColor.MatchString(language.Color) && !strings.ContainsAny(name, "\t\n") {
			names = append(names, name)
		}
	}
	sort.Strings(names)

	var out strings.Builder
	out.WriteString("# Language colours from GitHub Linguist (MIT License): " + source + "\n")
	out.WriteString("# Generated by internal/genlangcolors — do not edit. Format: name<TAB>#rrggbb\n")
	for _, name := range names {
		fmt.Fprintf(&out, "%s\t%s\n", name, languages[name].Color)
	}
	if err := os.WriteFile("langcolors.tsv", []byte(out.String()), 0o644); err != nil {
		return err
	}
	log.Printf("langcolors.tsv: %d languages", len(names))
	return nil
}
